GET http://localhost:5000/api/v1/auth/me
# Cookie: Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTI0MzAxYTE3YWE1OWZkNWU4NTJlYTAiLCJyb2xlcyI6WyJ1c2VyIl0sImVtYWlsIjoiZW16enlvbHV3b2xlQGdtYWlsLmNvbSIsInZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNzg3NDE5MzU4LCJleHAiOjE3ODc0NDgxNTh9.KD6V_D--__JfVkHJkc7xzSQVGou7QXAiu4T-dkAwKrA

# GET 