GET http://localhost:5000/

# All Course Endpoints (CRUD) has been created and tested, now it is time for User Endpoints and Authentication 

# USER ENDPOINTS

### Sign UP Locally
# POST http://localhost:5000/api/v1/signup
# Content-Type: application/json

# {
#     "email": "dynasty.dev241@gmail.com",
#     "password": "Dynastyda4#"
# }
POST http://localhost:5000/api/v1/signup
Content-Type: application/json

{
    "fullName": "Dynasty",
    "email": "dynastydagreat@gmail.com",
    "password": "Dynastyda4#"
}


### Test New Sign Up Route --> Updated user model
POST http://localhost:5000/api/v1/signup
Content-Type: application/json

{
    "fullName": "Mojiboye Emmanuel Oluwole",
    "email": "emzzyoluwole@gmail.com",
    "password": "Dynastyda2*"
}

# {
#     "fullName": "Mojiboye Emmanuel Oluwole",
#     "email": "dynasty.dev241@gmail.com",
#     "password": "Dynastyda2*"
# }


# {
#     "fullName": "Ben John Doe",
#     "email": "dynaman@email.com",
#     "password": "Dynadam2*"
# }

### Sign Up On Prod
POST  https://youdemi-fullstack.onrender.com/api/v1/signup
Content-Type: application/json

{
    "fullName": "Mojiboye Emmanuel Oluwole",
    "email": "emzzyoluwole@gmail.com",
    "password": "Dynastyda2*"
}

### Sign In Locally
POST http://localhost:5000/api/v1/signin
Content-Type: application/json

{
    "email": "dynastydagreat@gmail.com",
    "password": "Dynastyda4#"
}

# {
#     "email": "emzzyoluwole@gmail.com",
#     "password": "Dynastyda22#"
# }


# {
#     "email": "dynasty.dev241@gmail.com",
#     "password": "Dynastyda2#"
# }

# {
#     "email": "dynasty.dev241@gmail.com",
#     "password": "Dynastyda4#"
# }




### Sign In On Prod
POST  https://youdemi-fullstack.onrender.com/api/v1/signin
Content-Type: application/json

{
    "email": "dynastydagreat@gmail.com",
    "password": "Dynastyda4#"
}

# {
#     "email": "subomioguns07@gmail.com",
#     "password": "Dynastyda4#"
# }

# {
#     "email": "emazon@email.com",
#     "password": "Emazonda2**"
# }

### Sign Out
POST http://localhost:5000/api/v1/signout

### SEND VERIFICATION CODE TO EMAIL
PATCH http://localhost:5000/api/v1/send-verification-code
Content-Type: application/json 
client: not-browser

{
    "email": "dynastydagreat@gmail.com"
}

### VERIFY VERIFICATION CODE
PATCH http://localhost:5000/api/v1/verify-verification-code
Content-Type: application/json
client: not-browser 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGNmOTA0ODIyMWUwY2U4NzdiNWU2ZDYiLCJlbWFpbCI6ImR5bmFzdHlkYWdyZWF0QGdtYWlsLmNvbSIsInZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNzU4NDM0MDY3LCJleHAiOjE3NTg0NjI4Njd9.LiYwMlmRCZpoTPwEapeEaAVGYs5M6MRRrOwQMRO4yik

{
    "email": "dynastydagreat@gmail.com",
    "providedCode": 919476
}

### CHANGE PASSWORD
# PATCH http://localhost:5000/api/v1/change-password
# Content-Type: application/json
# client: not-browser
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODkzMWM3YzlmMzVjMmYyNzBmMTJjMDkiLCJlbWFpbCI6ImR5bmFzdHkuZGV2MjQxQGdtYWlsLmNvbSIsInZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTYxMzM2OTMsImV4cCI6MTc1NjE2MjQ5M30.yMxCgG6U6iK4rYJs1lB0YhN7znhpmBQ5e0ChTr0AZAk
# {
#     "oldPassword": "Emazonda44**",
#     "newPassword": "Dynastyda4#"
# }

### SEND RESET PASSWORD CODE --> LOCAL
PATCH http://localhost:5000/api/v1/send-forgot-password-code
Content-Type: application/json 

{
    "email": "emzzyoluwole@gmail.com"
}

### SEND RESET PASSWORD CODE --> PROD
# PATCH  https://youdemi-fullstack.onrender.com/api/v1/signin
# Content-Type: application/json
# client: not-browser
# Authorization: Bearer 

### VERIFY RESET PASSWORD CODE
PATCH http://localhost:5000/api/v1/verify-forgot-password-code
Content-Type: application/json
client: not-browser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGNiYjgyYmRkMmFmZTQ1MzQyYjIyNDgiLCJlbWFpbCI6ImVtenp5b2x1d29sZUBnbWFpbC5jb20iLCJ2ZXJpZmllZCI6dHJ1ZSwiaWF0IjoxNzU4MTgzMTkxLCJleHAiOjE3NTgyMTE5OTF9.h82lCBIOkzyV1wmwDYuPMpmLLMHOmW_YcRqKnVqOplU

{   "fullName": "Mojiboye Emmanuel Oluwole",
    "email": "emzzyoluwole@gmail.com",
    "providedCode": "167827",
    "newPassword": "Dynastyda22#"
}

### SEND RESET PASSWORD CODE --> PROD
PATCH https://youdemi-fullstack.onrender.com/api/v1/send-forgot-password-code
Content-Type: application/json 
client: not-browser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGNmOTA0ODIyMWUwY2U4NzdiNWU2ZDYiLCJlbWFpbCI6ImR5bmFzdHlkYWdyZWF0QGdtYWlsLmNvbSIsInZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTg2MjkyMzksImV4cCI6MTc1ODY1ODAzOX0.64rMzPelvbdOemcIZ7wFY0n4QFQ_q8J1emQLsQAABFI

{
    "email": "dynastydagreat@gmail.com"
}


### COURSE ENDPOINTS
GET http://localhost:5000/api/v1/course/

### /courses
GET http://localhost:5000/api/v1/courses
client: not-browser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGNmOTA0ODIyMWUwY2U4NzdiNWU2ZDYiLCJlbWFpbCI6ImR5bmFzdHlkYWdyZWF0QGdtYWlsLmNvbSIsInZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTg0MzQyOTAsImV4cCI6MTc1ODQ2MzA5MH0.ykCXwvtn5xz1aGE-t76qcblT8pHbWqd5o_8es4FyE9c

### /courses/new
POST http://localhost:5000/api/v1/courses/new
Content-Type: application/json
client: not-browser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGNmOTA0ODIyMWUwY2U4NzdiNWU2ZDYiLCJlbWFpbCI6ImR5bmFzdHlkYWdyZWF0QGdtYWlsLmNvbSIsInZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTg0MzQyOTAsImV4cCI6MTc1ODQ2MzA5MH0.ykCXwvtn5xz1aGE-t76qcblT8pHbWqd5o_8es4FyE9c

{
    "title": "CSC 499",
    "description": "Quantum Computing"
}

### GET /courses/:id
GET http://localhost:5000/api/v1/courses/68cf94acfc13ebeee7288eb7
client: not-browser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGNmOTA0ODIyMWUwY2U4NzdiNWU2ZDYiLCJlbWFpbCI6ImR5bmFzdHlkYWdyZWF0QGdtYWlsLmNvbSIsInZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTg0MzQyOTAsImV4cCI6MTc1ODQ2MzA5MH0.ykCXwvtn5xz1aGE-t76qcblT8pHbWqd5o_8es4FyE9c

### PATCH /courses/:id

PATCH http://localhost:5000/api/v1/courses/68cf94acfc13ebeee7288eb7
Content-Type: application/json
client: not-browser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGNmOTA0ODIyMWUwY2U4NzdiNWU2ZDYiLCJlbWFpbCI6ImR5bmFzdHlkYWdyZWF0QGdtYWlsLmNvbSIsInZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTg0MzQyOTAsImV4cCI6MTc1ODQ2MzA5MH0.ykCXwvtn5xz1aGE-t76qcblT8pHbWqd5o_8es4FyE9c

{
    "title": "CSC 500",
    "description": "Artificial Intelligence x250"
}

### DELETE /courses/:id
DELETE  http://localhost:5000/api/v1/courses/68ac9c601add052956b07e82
Content-Type: application/json
client: not-browser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGNmOTA0ODIyMWUwY2U4NzdiNWU2ZDYiLCJlbWFpbCI6ImR5bmFzdHlkYWdyZWF0QGdtYWlsLmNvbSIsInZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTg0MzQyOTAsImV4cCI6MTc1ODQ2MzA5MH0.ykCXwvtn5xz1aGE-t76qcblT8pHbWqd5o_8es4FyE9c

### Testing Remote URL
GET https://youdemi-fullstack.onrender.com/api/v1/course


### GET /courses

GET https://youdemi-fullstack.onrender.com/api/v1/course/courses

### Creating A New Course Remotely
POST https://youdemi-fullstack.onrender.com/api/v1/course/courses/new
Content-Type: application/json

{
    "title": "CSC 333",
    "description": "Operating System"
}

### GET /:id
GET https://youdemi-fullstack.onrender.com/api/v1/course/courses/688e2f29d59f2c245339c9ae

### Updating A Course on the Remote Render Server

PATCH https://youdemi-fullstack.onrender.com/api/v1/course/courses/688e2f29d59f2c245339c9ae
Content-Type: application/json

{
    "title": "CSC 325",
    "description": "System Programming"
}

### Deleting a Course from the Remote Render Server

DELETE https://youdemi-fullstack.onrender.com/api/v1/course/courses/688e2f29d59f2c245339c9ae
